In [5]:
import pandas as pd
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine, text
from datetime import datetime
from dateutil.relativedelta import relativedelta

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

class Updater:
    def __init__(self):
        
        self.__get_engine()
        
    def __load_dotenv(self):
        load_dotenv()
        return {
            'user': os.getenv("DB_USER"),
            'password': os.getenv("DB_PASSWORD"),
            'host': '172.16.3.158',
            'port': os.getenv("DB_PORT"),
            'db_name': os.getenv("DB_NAME"),
            'schema': 'fin'
        }

    def __get_engine(self):
        conf = self.__load_dotenv()
        self.__engine = create_engine(f"postgresql+psycopg2://{conf['user']}:{conf['password']}@{conf['host']}:{conf['port']}/{conf['db_name']}")

    def read_sql_query(self, query):
        with self.__engine.begin() as con:
            return pd.read_sql_query(query, con)

    def pandas_to_db(self, df, table, exists):
        with self.__engine.connect() as con:
            df.to_sql(table, con, if_exists=exists, index=False, schema='fin')

In [7]:
upd = Updater()

In [16]:
query = """select distinct frc, 'АО "РТ-Техприемка"' as company  from fin.frc_index where rev_frc is true"""
upd.read_sql_query(query)

,frc,company
0,Стратегия и инвестиции,"АО ""РТ-Техприемка"""
1,Центр качества поставок,"АО ""РТ-Техприемка"""
2,Метрологическая служба,"АО ""РТ-Техприемка"""
3,"Система добровольной сертификации ""Ростех""","АО ""РТ-Техприемка"""
4,Оценка и технический контроль,"АО ""РТ-Техприемка"""
5,Центр компетенции и системы управления качеством ГК Ростех,"АО ""РТ-Техприемка"""
6,Инновации и инжиниринг,"АО ""РТ-Техприемка"""
7,Управление проектами и цифровизацией,"АО ""РТ-Техприемка"""
8,Прочие,"АО ""РТ-Техприемка"""
9,Направление продаж,"АО ""РТ-Техприемка"""
10,Специальные проекты,"АО ""РТ-Техприемка"""
11,Центр сертификации,"АО ""РТ-Техприемка"""
12,Центр обучения,"АО ""РТ-Техприемка"""

In [17]:
class YearUpdater:
    def __init__(self):
        self.__get_engine()

    def __load_dotenv(self):
        load_dotenv()
        return {
            'user': os.getenv("DB_USER"),
            'password': os.getenv("DB_PASSWORD"),
            'host': os.getenv("DB_HOST"),
            'port': os.getenv("DB_PORT"),
            'db_name': os.getenv("DB_NAME"),
            'schema': 'fin'
        }

    def __get_engine(self):
        conf = self.__load_dotenv()
        self.__engine = create_engine(f"postgresql+psycopg2://{conf['user']}:{conf['password']}@{conf['host']}:{conf['port']}/{conf['db_name']}")

    def __read_sql_query(self, query):
        with self.__engine.begin() as con:
            return pd.read_sql_query(query, con)

    def __get_all_frc(self):
        c_year = datetime.now().year
        query = f"""
            select distinct frc, 'АО "РТ-Техприемка"' as company  
            from fin.frc_index 
            where rev_frc is true
            """
        return self.__read_sql_query(query)


    def __get_all_dates(self):
        c_year = datetime.now().year
        return pd.DataFrame({'date_dt': [datetime(c_year, 1, 1).date() + relativedelta(months=i) for i in range(12)],
                            'estimate_date': [datetime(c_year, 1, 1).date()] * 12,
                            'est_amount': [None] * 12,
                            'hcl_amount': [None] * 12,
                            'contr_amount': [None] * 12})

    def update_table(self):
        company_frc = self.__get_all_frc()
        dates_amounts = self.__get_all_dates()
        result_df = company_frc.join(dates_amounts, how='cross')[['company', 'date_dt',
                                                                  'estimate_date', 'frc',
                                                                 'est_amount', 'hcl_amount', 'contr_amount']]
        return result_df
        # with self.__engine.connect() as con:
        #     result_df.to_sql("revenue_est_2025", con, schema='fin', if_exists='append', index=False)

In [18]:
yu = YearUpdater()
yu.update_table()

,company,date_dt,estimate_date,frc,est_amount,hcl_amount,contr_amount
0,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Стратегия и инвестиции,None,None,None
1,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Стратегия и инвестиции,None,None,None
2,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Стратегия и инвестиции,None,None,None
3,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Стратегия и инвестиции,None,None,None
4,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Стратегия и инвестиции,None,None,None
5,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Стратегия и инвестиции,None,None,None
6,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Стратегия и инвестиции,None,None,None
7,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Стратегия и инвестиции,None,None,None
8,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Стратегия и инвестиции,None,None,None
9,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Стратегия и инвестиции,None,None,None
10,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Стратегия и инвестиции,None,None,None
11,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Стратегия и инвестиции,None,None,None
12,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Центр качества поставок,None,None,None
13,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Центр качества поставок,None,None,None
14,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Центр качества поставок,None,None,None
15,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Центр качества поставок,None,None,None
16,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Центр качества поставок,None,None,None
17,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Центр качества поставок,None,None,None
18,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Центр качества поставок,None,None,None
19,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Центр качества поставок,None,None,None
20,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Центр качества поставок,None,None,None
21,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Центр качества поставок,None,None,None
22,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Центр качества поставок,None,None,None
23,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Центр качества поставок,None,None,None
24,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Метрологическая служба,None,None,None
25,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Метрологическая служба,None,None,None
26,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Метрологическая служба,None,None,None
27,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Метрологическая служба,None,None,None
28,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Метрологическая служба,None,None,None
29,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Метрологическая служба,None,None,None
30,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Метрологическая служба,None,None,None
31,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Метрологическая служба,None,None,None
32,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Метрологическая служба,None,None,None
33,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Метрологическая служба,None,None,None
34,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Метрологическая служба,None,None,None
35,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Метрологическая служба,None,None,None
36,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
37,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
38,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
39,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
40,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
41,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
42,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
43,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
44,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
45,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
46,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
47,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,"Система добровольной сертификации ""Ростех""",None,None,None
48,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Оценка и технический контроль,None,None,None
49,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Оценка и технический контроль,None,None,None
50,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Оценка и технический контроль,None,None,None
51,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Оценка и технический контроль,None,None,None
52,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Оценка и технический контроль,None,None,None
53,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Оценка и технический контроль,None,None,None
54,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Оценка и технический контроль,None,None,None
55,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Оценка и технический контроль,None,None,None
56,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Оценка и технический контроль,None,None,None
57,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Оценка и технический контроль,None,None,None
58,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Оценка и технический контроль,None,None,None
59,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Оценка и технический контроль,None,None,None
60,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
61,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
62,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
63,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
64,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
65,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
66,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
67,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
68,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
69,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
70,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
71,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Центр компетенции и системы управления качеством ГК Ростех,None,None,None
72,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Инновации и инжиниринг,None,None,None
73,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Инновации и инжиниринг,None,None,None
74,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Инновации и инжиниринг,None,None,None
75,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Инновации и инжиниринг,None,None,None
76,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Инновации и инжиниринг,None,None,None
77,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Инновации и инжиниринг,None,None,None
78,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Инновации и инжиниринг,None,None,None
79,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Инновации и инжиниринг,None,None,None
80,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Инновации и инжиниринг,None,None,None
81,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Инновации и инжиниринг,None,None,None
82,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Инновации и инжиниринг,None,None,None
83,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Инновации и инжиниринг,None,None,None
84,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
85,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
86,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
87,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
88,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
89,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
90,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
91,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
92,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
93,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
94,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
95,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Управление проектами и цифровизацией,None,None,None
96,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Прочие,None,None,None
97,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Прочие,None,None,None
98,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Прочие,None,None,None
99,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Прочие,None,None,None
100,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Прочие,None,None,None
101,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Прочие,None,None,None
102,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Прочие,None,None,None
103,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Прочие,None,None,None
104,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Прочие,None,None,None
105,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Прочие,None,None,None
106,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Прочие,None,None,None
107,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Прочие,None,None,None
108,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Направление продаж,None,None,None
109,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Направление продаж,None,None,None
110,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Направление продаж,None,None,None
111,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Направление продаж,None,None,None
112,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Направление продаж,None,None,None
113,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Направление продаж,None,None,None
114,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Направление продаж,None,None,None
115,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Направление продаж,None,None,None
116,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Направление продаж,None,None,None
117,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Направление продаж,None,None,None
118,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Направление продаж,None,None,None
119,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Направление продаж,None,None,None
120,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Специальные проекты,None,None,None
121,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Специальные проекты,None,None,None
122,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Специальные проекты,None,None,None
123,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Специальные проекты,None,None,None
124,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Специальные проекты,None,None,None
125,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Специальные проекты,None,None,None
126,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Специальные проекты,None,None,None
127,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Специальные проекты,None,None,None
128,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Специальные проекты,None,None,None
129,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Специальные проекты,None,None,None
130,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Специальные проекты,None,None,None
131,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Специальные проекты,None,None,None
132,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Центр сертификации,None,None,None
133,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Центр сертификации,None,None,None
134,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Центр сертификации,None,None,None
135,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Центр сертификации,None,None,None
136,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Центр сертификации,None,None,None
137,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Центр сертификации,None,None,None
138,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Центр сертификации,None,None,None
139,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Центр сертификации,None,None,None
140,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Центр сертификации,None,None,None
141,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Центр сертификации,None,None,None
142,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Центр сертификации,None,None,None
143,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Центр сертификации,None,None,None
144,"АО ""РТ-Техприемка""",2025-01-01,2025-01-01,Центр обучения,None,None,None
145,"АО ""РТ-Техприемка""",2025-02-01,2025-01-01,Центр обучения,None,None,None
146,"АО ""РТ-Техприемка""",2025-03-01,2025-01-01,Центр обучения,None,None,None
147,"АО ""РТ-Техприемка""",2025-04-01,2025-01-01,Центр обучения,None,None,None
148,"АО ""РТ-Техприемка""",2025-05-01,2025-01-01,Центр обучения,None,None,None
149,"АО ""РТ-Техприемка""",2025-06-01,2025-01-01,Центр обучения,None,None,None
150,"АО ""РТ-Техприемка""",2025-07-01,2025-01-01,Центр обучения,None,None,None
151,"АО ""РТ-Техприемка""",2025-08-01,2025-01-01,Центр обучения,None,None,None
152,"АО ""РТ-Техприемка""",2025-09-01,2025-01-01,Центр обучения,None,None,None
153,"АО ""РТ-Техприемка""",2025-10-01,2025-01-01,Центр обучения,None,None,None
154,"АО ""РТ-Техприемка""",2025-11-01,2025-01-01,Центр обучения,None,None,None
155,"АО ""РТ-Техприемка""",2025-12-01,2025-01-01,Центр обучения,None,None,None