In [1]:
import pandas as pd
import sqlite3 as sq

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
with sq.connect('db.sqlite3') as con:
    db_data = pd.read_sql_query('select * from frc_user;', con)

In [5]:
db_data

,id,frc,user,email,login
0,1,admin,Кондратенко Денис Анатольевич,d.kondratenko@rt-techpriemka.ru,d.kondratenko
1,2,admin,Коньшин Дмитрий Сергеевич,d.konshin@rt-techpriemka.ru,d.konshin
2,3,admin,Чайковский Илья Сергеевич,i.chaykovskiy@rt-techpriemka.ru,i.chaykovskiy
3,4,Административно-хозяйственное обеспечение,Наумова Ирина Сергеевна,i.naumova@rt-techpriemka.ru,i.naumova
4,5,Административно-хозяйственное обеспечение,Шмелев Алексей Викторович,a.shmelev@rt-techpriemka.ru,a.shmelev
5,6,Бухгалтерия,Кузнецова Елена Анатольевна,ea.kuznetsova@rt-techpriemka.ru,ea.kuznetsova
6,7,Бухгалтерия,Фролов Евгений Валерьевич,e.frolov@rt-techpriemka.ru,e.frolov
7,8,Внутренняя система менеджмента качества,Михайлов Павел Михайлович,p.mihaylov@rt-techpriemka.ru,p.mihaylov
8,9,Инновации и инжиниринг,Дряев Георгий Георгиевич,g.dryaev@rt-techpriemka.ru,g.dryaev
9,10,Инновации и инжиниринг,Ульянов Евгений Ильич,e.ulyanov@rt-techpriemka.ru,e.ulyanov
10,11,Информационная безопасность,Воропаев Дмитрий Александрович,d.voropaev@rt-techpriemka.ru,d.voropaev
11,12,Информационное обеспечение,Дорохин Богдан Владимирович,b.dorohin@rt-techpriemka.ru,b.dorohin
12,13,Информационное обеспечение,Чебыкин Сергей Владимирович,s.chebykin@rt-techpriemka.ru,s.chebykin
13,14,Коммуникации и аналитика,Аликина Наталья Алексеевна,n.alikina@rt-techpriemka.ru,n.alikina
14,15,Консалтинг,Шевяков Роман Александрович,r.shevyakov@rt-techpriemka.ru,r.shevyakov
15,16,Метрологическая служба,Кокорев Андрей Александрович,a.kokorev@rt-techpriemka.ru,a.kokorev
16,17,Направление продаж,Запорожский Вячеслав Александрович,v.zaporozhskiy@rt-techpriemka.ru,v.zaporozhskiy
17,18,Направление продаж,Моисеенко Виталий Евгеньевич,v.moiseenko@rt-techpriemka.ru,v.moiseenko
18,19,Организационное и корпоративное развитие,Волкова Наталья Васильевна,n.volkova@rt-techpriemka.ru,n.volkova
19,20,Организационное и корпоративное развитие,Мазур Алексей Борисович,a.mazur@rt-techpriemka.ru,a.mazur
20,21,Организация закупок,Карташков Павел Владимирович,p.kartashkov@rt-techpriemka.ru,p.kartashkov
21,22,Охрана труда,Ясюкевич Антон Александрович,a.yasyukevich@rt-techpriemka.ru,a.yasyukevich
22,23,Оценка и технический контроль,Ткачев Сергей Владимирович,s.tkachev@rt-techpriemka.ru,s.tkachev
23,24,Правовое обеспечение и корпоративное управление,Токаева Хеда Мовладовна,h.tokaeva@rt-techpriemka.ru,h.tokaeva
24,25,Стратегия и инвестиции,Виноградов Всеволод Владимирович,v.vinogradov@rt-techpriemka.ru,v.vinogradov
25,26,Стратегия и инвестиции,Малиновский Ярослав Владимирович,ya.malinovskiy@rt-techpriemka.ru,ya.malinovskiy
26,27,Управление персоналом,Ветрова Наталья Андреевна,n.vetrova@rt-techpriemka.ru,n.vetrova
27,28,Управление персоналом,Радченко Наталья Владимировна,n.radchenko@rt-techpriemka.ru,n.radchenko
28,29,Управление проектами и цифровизацией,Леонов Александр Владимирович,a.leonov@rt-techpriemka.ru,a.leonov
29,30,Центр качества поставок,Захарова Алена Станиславовна,a.zaharova@rt-techpriemka.ru,a.zaharova
30,31,Центр компетенции и системы управления качеством ГК Ростех,Никулин Василий Семенович,v.nikulin@rt-techpriemka.ru,v.nikulin
31,32,Центр сертификации,Грудцов Иван Александрович,i.grudcov@rt-techpriemka.ru,i.grudcov
32,33,Центр сертификации,Кошелева Елизавета Робертовна,e.kosheleva@rt-techpriemka.ru,e.kosheleva
33,34,Экономика и финансы,Агафонова Мария Аркадьевна,m.agafonova@rt-techpriemka.ru,m.agafonova
34,35,Экономика и финансы,Смогунов Алексей Викторович,a.smogunov@rt-techpriemka.ru,a.smogunov
35,36,Экономическая и корпоративная безопасность,Исраилов Ваха Алхазурович,v.israilov@rt-techpriemka.ru,v.israilov
36,37,Направление продаж,Моисеенко Виталий Евгеньевич,v.moiseenko@rt-techpriemka.ru,v.moiseenko
37,38,Оценка и технический контроль,Ткачев Сергей Владимирович,s.tkachev@rt-techpriemka.ru,s.tkachev
38,39,Стратегия и инвестиции,Виноградов Всеволод Владимирович,v.vinogradov@rt-techpriemka.ru,v.vinogradov
39,40,Управление проектами и цифровизацией,Леонов Александр Владимирович,a.leonov@rt-techpriemka.ru,a.leonov
40,41,Центр качества поставок,Захарова Алена Станиславовна,a.zaharova@rt-techpriemka.ru,a.zaharova
41,42,Центр компетенции и системы управления качеством ГК Ростех,Никулин Василий Семенович,v.nikulin@rt-techpriemka.ru,v.nikulin
42,43,Центр обучения,Ефремов Василий Петрович,v.efremov@rtqualityplus.ru,v.efremov
43,44,Центр сертификации,Ефремов Василий Петрович,v.efremov@rtqualityplus.ru,v.efremov
44,45,Инновации и инжиниринг,Дряев Георгий Георгиевич,g.dryaev@rt-techpriemka.ru,g.dryaev
45,46,Направление продаж,Запорожский Вячеслав Александрович,v.zaporozhskiy@rt-techpriemka.ru,v.zaporozhskiy
46,47,Стратегия и инвестиции,Малиновский Ярослав Владимирович,ya.malinovskiy@rt-techpriemka.ru,ya.malinovskiy
47,48,Центр обучения,Кошелева Елизавета Робертовна,e.kosheleva@rt-techpriemka.ru,e.kosheleva
48,49,Центр сертификации,Грудцов Иван Александрович,i.grudcov@rt-techpriemka.ru,i.grudcov

In [6]:
exl_data = pd.read_excel('new_frc_users.xlsx', sheet_name='для ввода прогноза')

In [7]:
exl_data

,Unnamed: 0,ЦФО,Ф,И,О,почта,Ф.1,И.1,О.1,почта.1
0,4,Инновации и инжиниринг,Ульянов,Евгений,Ильич,e.ulyanov@rt-techpriemka.ru,Дряев,Георгий,Георгиевич,g.dryaev@rt-techpriemka.ru
1,10,Направление продаж,Моисеенко,Виталий,Евгеньевич,v.moiseenko@rt-techpriemka.ru,Запорожский,Вячеслав,Александрович,v.zaporozhskiy@rt-techpriemka.ru
2,14,Оценка и технический контроль,Ткачев,Сергей,Владимирович,s.tkachev@rt-techpriemka.ru,NaN,NaN,NaN,NaN
3,16,Стратегия и инвестиции,Виноградов,Всеволод,Владимирович,v.vinogradov@rt-techpriemka.ru,Малиновский,Ярослав,Владимирович,ya.malinovskiy@rt-techpriemka.ru
4,18,Управление проектами и цифровизацией,Леонов,Александр,Владимирович,a.leonov@rt-techpriemka.ru,NaN,NaN,NaN,NaN
5,19,Центр качества поставок,Захарова,Алена,Станиславовна,a.zaharova@rt-techpriemka.ru,NaN,NaN,NaN,NaN
6,20,Центр компетенции и системы управления качеством ГК Ростех,Никулин,Василий,Семенович,v.nikulin@rt-techpriemka.ru,NaN,NaN,NaN,NaN
7,21,Центр обучения,Ефремов,Василий,Петрович,v.efremov@rtqualityplus.ru,Кошелева,Елизавета,Робертовна,e.kosheleva@rt-techpriemka.ru
8,22,Центр сертификации,Ефремов,Василий,Петрович,v.efremov@rtqualityplus.ru,Грудцов,Иван,Александрович,i.grudcov@rt-techpriemka.ru

In [8]:
user_to_insert = pd.concat([
( 
    exl_data
    .assign(user = lambda x: x['Ф'] + ' ' + x['И'] + ' ' + x['О'])
    .rename({'ЦФО': 'frc', 'почта': 'email'}, axis=1)
    .dropna(subset='email')
    .assign(login = lambda x: x['email'].apply(lambda x: x.split('@')[0]))
    [['frc', 'user', 'email', 'login']]
),
( 
    exl_data
    .assign(user = lambda x: x['Ф.1'] + ' ' + x['И.1'] + ' ' + x['О.1'])
    .rename({'ЦФО': 'frc', 'почта.1': 'email'}, axis=1)
    .dropna(subset='email')
    .assign(login = lambda x: x['email'].apply(lambda x: x.split('@')[0]))
    [['frc', 'user', 'email', 'login']]
)
]).iloc[1:,:]

In [10]:
user_to_insert.to_sql('frc_user', con, if_exists='append', index=False)

13